language: node_js
node_js:
- '7'
deploy:
  skip_cleanup: true
  provider: npm
  email: gisli.konrad@gmail.com
  api_key:
    secure: IJNujj6kPGPmfM8CUS2ryifN9ujH8N/vMzZ5b0VEVMpue0Ig5FfjQrcCAG9dgEBlJWx/Kd6/MsqxRMN/FiyVpsFIKS743TXCvLoNK+4EnbtNHIN9f7p1pVIaRfbt+MWfIwI8cCLlcD3i+R82IB6dQ1A9R8Vi5ZAk2tExXx/Fx5K3bWvz+idxqZtj+E4QhTWdOU+0vL3QdFiSJpxD669y/RTkQflRwA+eDKKkwreiTa181gY3wmPlBUba5Z6m1+DjszsnH1wMLunaWU8UCc0tO6rYmovN3q40T3MFbjvTwEnEgqPvhruakVAOWdhqGrE8Ty1mKHOciL4kzEi2JRiuui8SQP0Vgh8NM/gwROIXoExpM+YDjMVfWGmga1YPNRAQhwgPhZkPQvQfQhVLoiLO5062T+duqWgTKAD7PQXzreQRzt36VZTdIdXrCvZy8AnFvTP3Y9UrGSeLX9qyyYljz9zmyhzX/KAn9cN9FpMg4Vdmoh9lDLRzgoeYg7KxYeqgFYd9q/tFJlMUWUy4vuvhwgzSdWCbpXyIUnGl6s5YLulYOGIII/4CarQRqmU7lVGMILELxf9sFbg7+pp+QSGP8Sc4pf24Hj6IshzWWMpStHI4y7huCwqzM8tZaKZe+QeKGlBpvczlWg0gv1xLwCLCg7ixiMmJKrPLuY92rEGR0vM=
  on:
    tags: true
    repo: gislikonrad/swagger-schema-ts
